"""Refactor skin cancer data table

Revision ID: 0ba70bd167bd
Revises: 10445a735b90
Create Date: 2025-03-14 20:15:39.537838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba70bd167bd'
down_revision = '10445a735b90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skin_cancer_data', sa.Column('data_type', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_skin_cancer_data_data_type'), 'skin_cancer_data', ['data_type'], unique=False)
    op.drop_column('skin_cancer_data', 'age_specific_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skin_cancer_data', sa.Column('age_specific_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_skin_cancer_data_data_type'), table_name='skin_cancer_data')
    op.drop_column('skin_cancer_data', 'data_type')
    # ### end Alembic commands ###